package:
  name: gdal2
  version: "2.2.1"

source:
    fn: gdal-2.2.1.tar.gz
    url: http://download.osgeo.org/gdal/2.2.1/gdal-2.2.1.tar.gz
    md5: 785acf2b0cbf9d56d37c9044d0ee2505 

requirements:
  build:
    - python >=3.6
    - numpy >=1.13
    - geos >=3.5
    - hdf4 ==4.2.12-0
    - hdf5 
    - proj4
    - xerces-c
    - libiconv
  run:
    - python >=3.6
    - numpy >=1.13
    - geos >=3.5
    - hdf4 ==4.2.12-0
    - hdf5 
    - proj4
    - xerces-c
    - libiconv

build:
  number: 1

test:
  files:
    - os1_hw.py
    - sites.dbf
    - sites.sbn
    - sites.sbx
    - sites.shp
    - sites.shx
  imports:
    - osgeo

about:
  home: http://www.gdal.org/
  license: MIT
  summary: The Geospatial Data Abstraction Library (GDAL) Version 2.2.1 Built with all command line tools and with GEOS and HDF4/HDF5 support.
